os: linux
language: node_js
node_js:
  - {{cookiecutter.node_version}}
dist: focal
install:
  - npm i
cache:
  directories:
    - "~/.npm"
    - "~/.cache"
  npm: true
addons:
  sonarcloud:
    organization: "{{cookiecutter.sonar_org}}"
stages:
  - name: Quality checks
  - name: Unit test & sonar-scanner
jobs:
  include:
    - stage: Quality checks
      script:
        - npm run prettier:verify
        - npm run eslint:verify
        - npx snyk test
      name: Quality checks
    - stage: Unit test & sonar-scanner
      script:
        - npm test
        - sonar-scanner -D sonar.login=$SONAR_TOKEN
      name: Unit test & sonar-scanner
      env: Unit test & sonar-scanner
